#include<iostream>
using namespace std; 
main()
{ 
     cout<<"number 1";
     int N1;
     cin>>N1;
     cout<<"number 2";
     int N2;
     cin>>N2;
     cout<<"number 3";
     int N3;
     cin>>N3;
     cout<<"number 4";
     int N4;
     cin>>N4;
     cout<<"number 5";
     int N5;
     cin>>N5;
     cout<<"number 6";
     int N6;
     cin>>N6;
     cout<<"number 7";
     int N7;
     cin>>N7;
     cout<<"number 8";
     int N8;
     cin>>N8;
     cout<<"number 9";
     int N9;
     cin>>N9;
     cout<<"number 10";
     int N10;
     cin>>N10;
     cout<<"number 11";
     int N11;
     cin>>N11;
     cout<<"number 12";
     int N12;
     cin>>N12;
     cout<<"number 13";
     int N13;
     cin>>N13;
     cout<<"number 14";
     int N14;
     cin>>N14;
     cout<<"number 15";
     int N15;
     cin>>N15;
     int add;
     add=N1+N2+N3+N4+N5;
     int mult;
     mult=N6*N7*N8*N9*N10;
     int sub;
     sub=N11-N12-N13-N14-N15;
     int result;
     result=(add+mult)-sub;
     cout<<"final result"<<result;
}